# New ports collection makefile for:	reallyenglish-nagios-plugins
# Date created:		2010-06-30
# Whom:			Tomoyuki Sakurai <tomoyukis@reallyenglish.com>
#
# $FreeBSD$
#

PORTNAME=	reallyenglish-nagios-plugins
PORTVERSION=	0.2
#PORTREVISION=	0
CATEGORIES=	sysutils
MASTER_SITES=	http://journal.reallyenglish.com/
EXTRACT_SUFX=	.tgz

MAINTAINER=	tomoyukis@reallyenglish.com
COMMENT=	Nagios plugins at reallyenglish

RUN_DEPENDS+=	${LOCALBASE}/libexec/nagios/utils.sh:${PORTSDIR}/net-mgmt/nagios-plugins

NO_BUILD=	Yes

.include <bsd.port.mk>
