# New ports collection makefile for:	Ruby replacement for json
# Date created:		Jul 9, 2007
# Whom:			Cheng-Lung Sung <clsung@FreeBSD.org>
#
# $FreeBSD: ports/devel/rubygem-json/Makefile,v 1.13 2010/07/12 08:35:32 clsung Exp $
#

PORTNAME=	json
PORTVERSION=	1.4.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Parse JSON texts and generate them from ruby data structures

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/edit_json.rb bin/prettify_json.rb

.include <bsd.port.mk>
