# New ports collection makefile for:   ezjail
# Date created:        1 September 2005
# Whom:                erdgeist
#
# $FreeBSD: ports/sysutils/ezjail/Makefile,v 1.12 2010/03/04 14:57:25 wxs Exp $
#

PORTNAME=	ezjail
PORTVERSION=	3.1
CATEGORIES=	sysutils
MASTER_SITES=	http://erdgeist.org/arts/software/ezjail/

MAINTAINER=	erdgeist@erdgeist.org
COMMENT=	A framework to easily create, manipulate and run FreeBSD jails

USE_BZIP2=	yes

MAN1=		ezjail-admin.1
MAN5=		ezjail.5 ezjail.conf.5

.include <bsd.port.mk>
