# New ports collection makefile for:	rubygem-syslog-logger
# Date created:		2011-08-25
# Whom:			Tomoyuki Sakurai <tomoyukis@reallyenglish.com>
#
# $FreeBSD$
#

PORTNAME=	syslog-logger
PORTVERSION=	1.6.4
#PORTREVISION=	0
CATEGORIES=	sysutils
MASTER_SITES=	RG

MAINTAINER=	tomoyukis@reallyenglish.com
COMMENT=	improved Logger replacement that logs to syslog

USE_RUBY=	Yes
USE_RUBYGEMS=	Yes
RUBYGEM_AUTOPLIST=	Yes

.include <bsd.port.mk>
